// codemap/1 §6 — language profiles.
//
// docPolicy decides what happens to ORDINARY comments, and is the reason this framework can be
// dropped into ecosystems whose convention is the opposite of "few comments" (Go's godoc,
// Laravel's PHPStan docblocks) without being uninstalled on day one.
//
//   banned                -> a prose comment is CM001
//   allowed               -> prose comments are accepted; only cm: grammar is enforced
//   required-on-exported  -> a comment block directly above an exported declaration is exempt

const COMMON_EXEMPT = [
  /^cm:ignore\b/,
  /^(Copyright|SPDX-License-Identifier)\b/i,
  /^@generated\b/,
];

const TS_EXEMPT = [
  /^@ts-(expect-error|ignore|nocheck|check)\b/,
  /^eslint-(disable|enable)/,
  /^biome-ignore\b/,
  /^(prettier|dprint|deno-lint)-ignore\b/,
  /^(istanbul|c8|v8) ignore\b/,
  /^#(region|endregion)\b/,
  /^# sourceMappingURL=/,
  /^@__PURE__/,
  /^@(vite-ignore|jsx|jsxImportSource|vitest-environment|license|preserve)\b/,
  /^<reference\b/,
  /^@type\b/, // load-bearing under checkJs
];

const GO_EXEMPT = [
  /^go:[a-z]+/, // go:build, go:generate, go:embed
  /^\+build\b/,
  /^nolint\b/,
  /^lint:ignore\b/,
  /^export\s/, // cgo
  /^Deprecated:/,
];

const PHP_EXEMPT = [
  /^@(phpstan|psalm)-/,
  /^@(var|param|return|throws|deprecated|internal)\b/,
  /^phpcs:/,
  /^@codeCoverageIgnore/,
  /^@noinspection\b/,
  /^@SuppressWarnings\b/,
];

const PY_EXEMPT = [
  /^!/, // shebang
  /^-\*- coding/,
  /^coding[:=]/,
  /^type:\s/,
  /^noqa\b/,
  /^pragma:/,
  /^(pylint|mypy|ruff|pyright|isort|doctest):/,
  /^fmt:\s?(on|off)/,
  /^nosec\b/,
  /^black\b/,
];

const RUST_EXEMPT = [
  /^SAFETY:/, // clippy::undocumented_unsafe_blocks requires it
  /^rustfmt::skip/,
  /^clippy::/,
];

const SQL_EXEMPT = [
  /^>\s*statement-breakpoint/, // drizzle
  /^\+goose\b/,
  /^migrate:/,
];

const SH_EXEMPT = [/^!/, /^shellcheck\b/];

/** A file whose head carries one of these is skipped entirely. */
export const GENERATED_MARKERS = [
  /Code generated .*DO NOT EDIT/,
  /@generated\b/,
  /AUTO[- ]GENERATED/i,
  /DO NOT EDIT THIS FILE/i,
  /_ide_helper/,
];

/**
 * strDelims  — quote characters, longest first (triple quotes before single).
 * multiline  — delimiters that legitimately span lines; every other one resets at EOL so a
 *              stray apostrophe in prose cannot desync the scanner for the rest of the file.
 */
const P = {
  ts: {
    id: 'ts',
    lineLeaders: ['//'],
    docLineLeaders: [],
    blockOpens: [['/**', '*/'], ['/*', '*/']],
    docBlockOpens: ['/**'],
    strDelims: ['"', "'", '`'],
    multiline: ['`'],
    docPolicy: 'banned',
    // A /** */ block is documentation by form: the IDE surfaces it on hover, which is a consumer
    // with an immediate payoff (principle 1). Narration in a function body is the spam this exists
    // to kill, and that is always a line comment. So doc blocks are exempt and `//` prose is not —
    // simpler and more predictable than trying to decide which declarations deserve docs.
    docBlocksAllowed: true,
    exempt: [...COMMON_EXEMPT, ...TS_EXEMPT],
  },
  go: {
    id: 'go',
    lineLeaders: ['//'],
    docLineLeaders: [],
    blockOpens: [['/*', '*/']],
    docBlockOpens: [],
    strDelims: ['"', '`'],
    multiline: ['`'],
    docPolicy: 'required-on-exported',
    // godoc requires a comment above the package clause and above every EXPORTED declaration —
    // and only those. An unexported func must not be exempt, or the policy exempts everything.
    exportedDecl: /^(?:package\s+\w+|(?:func|type|const|var)\s+(?:\(\s*\w+\s+\*?\w+\s*\)\s+)?[A-Z]\w*)/,
    exempt: [...COMMON_EXEMPT, ...GO_EXEMPT],
  },
  php: {
    id: 'php',
    lineLeaders: ['//', '#'],
    docLineLeaders: [],
    blockOpens: [['/**', '*/'], ['/*', '*/']],
    docBlockOpens: ['/**'],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    exempt: [...COMMON_EXEMPT, ...PHP_EXEMPT],
  },
  py: {
    id: 'py',
    lineLeaders: ['#'],
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"""', "'''", '"', "'"],
    multiline: ['"""', "'''"],
    docPolicy: 'allowed', // docstrings are strings, not comments — out of scope by construction
    exempt: [...COMMON_EXEMPT, ...PY_EXEMPT],
  },
  rust: {
    id: 'rust',
    lineLeaders: ['///', '//!', '//'],
    docLineLeaders: ['///', '//!'],
    blockOpens: [['/*', '*/']],
    docBlockOpens: [],
    strDelims: ['"'], // ' is a lifetime marker in Rust, never a string opener
    multiline: ['"'],
    docPolicy: 'allowed',
    exempt: [...COMMON_EXEMPT, ...RUST_EXEMPT],
  },
  sql: {
    id: 'sql',
    lineLeaders: ['--'],
    docLineLeaders: [],
    blockOpens: [['/*', '*/']],
    docBlockOpens: [],
    strDelims: ["'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false, // annotations still parsed, so sideeffect edges can sit next to a trigger
    exempt: [...COMMON_EXEMPT, ...SQL_EXEMPT],
  },
  sh: {
    id: 'sh',
    lineLeaders: ['#'],
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false,
    exempt: [...COMMON_EXEMPT, ...SH_EXEMPT],
  },
  yaml: {
    id: 'yaml',
    lineLeaders: ['#'],
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false,
    exempt: COMMON_EXEMPT,
  },
};

const BY_EXT = {
  ts: P.ts, tsx: P.ts, mts: P.ts, cts: P.ts,
  js: P.ts, jsx: P.ts, mjs: P.ts, cjs: P.ts,
  vue: P.ts, svelte: P.ts,
  go: P.go,
  php: P.php,
  py: P.py, pyi: P.py,
  rs: P.rust,
  sql: P.sql,
  sh: P.sh, bash: P.sh, zsh: P.sh,
  yaml: P.yaml, yml: P.yaml, toml: P.yaml,
};

export const PROFILES = P;

export function profileFor(filePath) {
  const m = /\.([a-z0-9]+)$/i.exec(filePath);
  if (!m) return null;
  return BY_EXT[m[1].toLowerCase()] ?? null;
}

export function isGenerated(src) {
  const head = src.split('\n', 40).join('\n');
  return GENERATED_MARKERS.some((re) => re.test(head));
}
