// codemap/1 §6 — language profiles.
//
// docPolicy decides what happens to ORDINARY comments, and is the reason this framework can be
// dropped into ecosystems whose convention is the opposite of "few comments" (Go's godoc,
// Laravel's PHPStan docblocks) without being uninstalled on day one.
//
//   banned                -> a prose comment is CM001
//   allowed               -> prose comments are accepted; only cm: grammar is enforced
//   required-on-exported  -> a comment block directly above an exported declaration is exempt

import { scanComments } from './scan.mjs';

const COMMON_EXEMPT = [
  /^cm:ignore\b/,
  /^(Copyright|SPDX-License-Identifier)\b/i,
  /^@generated\b/,
];

const TS_EXEMPT = [
  /^@ts-(expect-error|ignore|nocheck|check)\b/,
  /^eslint-(disable|enable)/,
  /^biome-ignore\b/,
  /^i18n-allow\s*:/, // a consumer's own language gate requires this directive on non-English literals
  /^(prettier|dprint|deno-lint)-ignore\b/,
  /^(istanbul|c8|v8) ignore\b/,
  /^#(region|endregion)\b/,
  /^# sourceMappingURL=/,
  /^@__PURE__/,
  /^@(vite-ignore|jsx|jsxImportSource|vitest-environment|license|preserve)\b/,
  /^<reference\b/,
  /^@type\b/, // load-bearing under checkJs
];

const GO_EXEMPT = [
  /^go:[a-z]+/, // go:build, go:generate, go:embed
  /^\+build\b/,
  /^nolint\b/,
  /^lint:ignore\b/,
  /^export\s/, // cgo
  /^Deprecated:/,
];

const PHP_EXEMPT = [
  /^@(phpstan|psalm)-/,
  /^@(var|param|return|throws|deprecated|internal)\b/,
  /^phpcs:/,
  /^@codeCoverageIgnore/,
  /^@noinspection\b/,
  /^@SuppressWarnings\b/,
];

const PY_EXEMPT = [
  /^!/, // shebang
  /^-\*- coding/,
  /^coding[:=]/,
  /^type:\s/,
  /^noqa\b/,
  /^pragma:/,
  /^(pylint|mypy|ruff|pyright|isort|doctest):/,
  /^fmt:\s?(on|off)/,
  /^nosec\b/,
  /^black\b/,
];

const RUST_EXEMPT = [
  /^SAFETY:/, // clippy::undocumented_unsafe_blocks requires it
  /^rustfmt::skip/,
  /^clippy::/,
];

const SQL_EXEMPT = [
  /^>\s*statement-breakpoint/, // drizzle
  /^\+goose\b/,
  /^migrate:/,
];

const SH_EXEMPT = [/^!/, /^shellcheck\b/];

// cm:why Docker requires these three above everything else, so they cannot be moved below a header
//   comment and cannot be rewritten — the parser reads them, not a person
const DOCKER_EXEMPT = [/^syntax=/, /^escape=/, /^check=/];

/** How far into a file a generated-marker comment is still the file's own header. */
export const GENERATED_HEAD_LINES = 40;

/** A file whose head carries one of these is skipped entirely. */
export const GENERATED_MARKERS = [
  /Code generated .*DO NOT EDIT/,
  /@generated\b/,
  /AUTO[- ]GENERATED/i,
  /DO NOT EDIT THIS FILE/i,
  /_ide_helper/,
];

/**
 * strDelims  — quote characters, longest first (triple quotes before single).
 * multiline  — delimiters that legitimately span lines; every other one resets at EOL so a
 *              stray apostrophe in prose cannot desync the scanner for the rest of the file.
 */
const TS = {
  id: 'ts',
  // cm:why the RUNTIME, not the profile — §7.1 reads "different languages" as "cannot import each
  //   other", and an SFC imports .ts freely, so sfc inherits this and a literal they share is not a contract
  ecosystem: 'ts',
  lineLeaders: ['//'],
  docLineLeaders: [],
  blockOpens: [['/**', '*/'], ['/*', '*/']],
  docBlockOpens: ['/**'],
  strDelims: ['"', "'", '`'],
  multiline: ['`'],
  docPolicy: 'banned',
  // A /** */ block is documentation by form: the IDE surfaces it on hover, which is a consumer
  // with an immediate payoff (principle 1). Narration in a function body is the spam this exists
  // to kill, and that is always a line comment. So doc blocks are exempt and `//` prose is not —
  // simpler and more predictable than trying to decide which declarations deserve docs.
  docBlocksAllowed: true,
  // An ECMAScript directive prologue is the one construct the language itself requires ABOVE
  // everything else, so a header comment cannot get above it. Closed vocabulary (principle 3):
  // a general "string literal as a statement" rule would swallow a stray expression statement.
  prologue: /^\s*(['"])use (client|server|strict)\1\s*;?\s*$/,
  exempt: [...COMMON_EXEMPT, ...TS_EXEMPT],
};

const P = {
  ts: TS,
  // cm:why a template comments in HTML, not in TS's forms, and that is where a generator stamps a
  //   component's marker — without the form the marker is not comment text at all (ISS-28)
  // cm:guard exempt from prose BY FORM, never by a directive allowlist — a template has no per-site
  //   escape, so billing svelte-ignore would be a CM001 nobody can clear (ISS-28, rule in ISS-22)
  // cm:guard the spread comes FIRST — `id` after it, or TS's own id overwrites this profile's and
  //   every diagnostic, `cm ls` and `languages.sfc` silently address `ts` instead
  sfc: {
    ...TS,
    id: 'sfc',
    // cm:why shares TS's ecosystem and is still out of CM301: no measurement has ever covered an SFC,
    //   and admitting one would warn in every consumer Vue repo as a side effect of a refactor (ISS-32)
    advisoryTier: false,
    blockOpens: [...TS.blockOpens, ['<!--', '-->']],
    proseExemptBlockOpens: ['<!--'],
  },
  go: {
    id: 'go',
    lineLeaders: ['//'],
    docLineLeaders: [],
    blockOpens: [['/*', '*/']],
    docBlockOpens: [],
    strDelims: ['"', '`'],
    multiline: ['`'],
    docPolicy: 'required-on-exported',
    // godoc requires a comment above the package clause and above every EXPORTED declaration —
    // and only those. An unexported func must not be exempt, or the policy exempts everything.
    // cm:guard `func\s*\(` is deliberately NOT a group opener here — that is a method receiver, and
    //   admitting it would exempt every unexported method too
    exportedDecl: /^(?:package\s+\w+|(?:type|const|var)\s*\(|(?:func|type|const|var)\s+(?:\(\s*\w+\s+\*?\w+\s*\)\s+)?[A-Z]\w*)/,
    // cm:why godoc renders a field's and a method's doc exactly as it renders a top-level one, so the
    //   position-only rule flagged 3036 blocks the ecosystem asks authors to write (ISS-10)
    exportedMember: /^[A-Z]\w*/,
    // cm:guard the member rule holds ONLY inside these — capitalisation alone would exempt narration above
    //   a same-package call like `DoThing()`, which is the in-body bucket the policy exists to catch
    memberBlock: /^(?:type\s+[A-Z]\w*\s*(?:=\s*)?(?:struct|interface)\b|type\s*\(|const\s*\(|var\s*\()/,
    exempt: [...COMMON_EXEMPT, ...GO_EXEMPT],
  },
  php: {
    id: 'php',
    lineLeaders: ['//', '#'],
    docLineLeaders: [],
    blockOpens: [['/**', '*/'], ['/*', '*/']],
    docBlockOpens: ['/**'],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    exempt: [...COMMON_EXEMPT, ...PHP_EXEMPT],
  },
  py: {
    id: 'py',
    lineLeaders: ['#'],
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"""', "'''", '"', "'"],
    multiline: ['"""', "'''"],
    docPolicy: 'allowed', // docstrings are strings, not comments — out of scope by construction
    exempt: [...COMMON_EXEMPT, ...PY_EXEMPT],
  },
  rust: {
    id: 'rust',
    lineLeaders: ['///', '//!', '//'],
    docLineLeaders: ['///', '//!'],
    blockOpens: [['/*', '*/']],
    docBlockOpens: [],
    strDelims: ['"'], // ' is a lifetime marker in Rust, never a string opener
    multiline: ['"'],
    docPolicy: 'allowed',
    exempt: [...COMMON_EXEMPT, ...RUST_EXEMPT],
  },
  sql: {
    id: 'sql',
    lineLeaders: ['--'],
    docLineLeaders: [],
    blockOpens: [['/*', '*/']],
    docBlockOpens: [],
    strDelims: ["'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false, // annotations still parsed, so sideeffect edges can sit next to a trigger
    // cm:why these four carry annotations without their prose being policed, and no CM301 measurement
    //   covers them; `enforce` is NOT the knob for it — that is prose grammar, overridable per repo
    advisoryTier: false,
    exempt: [...COMMON_EXEMPT, ...SQL_EXEMPT],
  },
  sh: {
    id: 'sh',
    lineLeaders: ['#'],
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false,
    advisoryTier: false,
    exempt: [...COMMON_EXEMPT, ...SH_EXEMPT],
  },
  yaml: {
    id: 'yaml',
    lineLeaders: ['#'],
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false,
    advisoryTier: false,
    exempt: COMMON_EXEMPT,
  },
  docker: {
    // cm:why its own id rather than a reuse of yaml — the id is what `cm ls`, `cm help languages` and
    //   every diagnostic print, so a Dockerfile reporting as yaml misnames the file in its own error,
    //   and this is the only profile where Docker's parser directives can be exempt (ISS-25)
    id: 'docker',
    lineLeaders: ['#'],
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false,
    advisoryTier: false,
    exempt: [...COMMON_EXEMPT, ...DOCKER_EXEMPT],
  },
};

const BY_EXT = {
  ts: P.ts, tsx: P.ts, mts: P.ts, cts: P.ts,
  js: P.ts, jsx: P.ts, mjs: P.ts, cjs: P.ts,
  vue: P.sfc, svelte: P.sfc,
  go: P.go,
  php: P.php,
  py: P.py, pyi: P.py,
  rs: P.rust,
  sql: P.sql,
  sh: P.sh, bash: P.sh, zsh: P.sh,
  yaml: P.yaml, yml: P.yaml, toml: P.yaml,
};

const BY_BASENAME = {
  dockerfile: P.docker,
  containerfile: P.docker,
};

// cm:guard `<stem>.<variant>` takes an UNBOUNDED variant, so a stem here must be a word no
//   documentation or leftover file is named after — `.go` as a stem would swallow every Go file
const BASENAME_STEMS = Object.keys(BY_BASENAME);

// cm:why a documentation file is the one place a FALSE annotation outranks a missed one (§6): its
//   fenced examples are not declarations, and under a `#` leader a markdown heading is a comment,
//   so an example `# cm:edge` becomes a real edge whose stale target fails a consumer's CI with
//   CM102 in a repo that changed nothing. Ordering cannot spare it — `md` is in no profile either,
//   so it misses BY_EXT and reaches the stem rules regardless (ISS-25)
// cm:guard every spelling of a format already here must be here too — `adoc` and `asciidoc` denied
//   while `asc` resolved is the same CM102 break wearing the third name for one format (ISS-25)
const DOC_EXT_DENY = new Set([
  'md', 'mdx', 'markdown', 'mkd', 'mdown', 'mdwn', 'mmd', 'mdtxt', 'markdn',
  'qmd', 'rmd', 'txt', 'text', 'rst', 'adoc', 'asciidoc', 'asc', 'textile', 'html', 'htm',
]);

// cm:why junk is what a conflicted merge or `patch` writes, holding the PRE-merge annotations, so a
//   variant whose last component is one is refused outright — `Dockerfile.orig` beside a fixed
//   Dockerfile reported its stale edge as live. `example`/`sample`/`dist` are committed on purpose
//   and keep scanning, which is why one list cannot serve both (ISS-25)
const JUNK_WORDS = new Set(['bak', 'orig', 'rej', 'save', 'swp', 'tmp', 'old']);

export const PROFILES = P;

// cm:guard split on the dot and judged per component, never on the trailing extension alone:
//   `Dockerfile.md.bak` and `Dockerfile.markdown.old` are documentation whose doc word is not last,
//   and a trailing-only test read both as Dockerfiles (ISS-25)
function variantWords(variant) {
  return variant.replace(/~+$/, '').split('.').filter(Boolean);
}

function docDenied(variant) {
  return variantWords(variant).some((w) => DOC_EXT_DENY.has(w));
}

/** A leftover an editor or a merge wrote — never the file the repository builds from. */
function isLeftover(variant) {
  if (/~$/.test(variant)) return true;
  const words = variantWords(variant);
  return words.length > 0 && JUNK_WORDS.has(words[words.length - 1]);
}

// cm:guard extension first, basename second — a hit in BY_EXT wins, or `x.yml` resolves by a stem
//   rule and every YAML file in the tree changes profile
// cm:guard this is the single authority on what is scannable; registry.mjs asks it rather than
//   restating it, and the SCAN_EXT regex that used to be that second list is why Dockerfiles were
//   indexed by `cm ls` and invisible to `cm verify` at the same time (ISS-25)
export function profileFor(filePath) {
  const base = String(filePath).split(/[\\/]/).pop() ?? '';
  const ext = /\.([a-z0-9]+)$/i.exec(base)?.[1]?.toLowerCase();
  if (ext && BY_EXT[ext]) return BY_EXT[ext];

  const lower = base.toLowerCase();
  if (BY_BASENAME[lower]) return BY_BASENAME[lower];

  for (const stem of BASENAME_STEMS) {
    let variant = null;
    if (lower.startsWith(`${stem}.`)) variant = lower.slice(stem.length + 1);
    else if (lower.endsWith(`.${stem}`)) variant = lower.slice(0, -(stem.length + 1));
    if (variant === null) continue;
    if (docDenied(variant) || isLeftover(variant)) return null;
    return BY_BASENAME[stem];
  }
  return null;
}

// cm:guard the SINGLE authority on "can these two files import each other" — ask it, never restate it
//   from a literal; a second extension-keyed table in graph.mjs silently lost 5 extensions (ISS-32)
export function ecosystemOf(filePath) {
  const prof = profileFor(filePath);
  return prof ? (prof.ecosystem ?? prof.id) : null;
}

// cm:guard a pair of files in different languages CANNOT reference each other — measured, that was 26 of
//   36 hits in one repo, so firing there is a bug in the check and not a threshold to tune (§7.1)
// cm:guard opt out on the PROFILE and never on the extension — a new BY_EXT entry must inherit its
//   profile's answer, and eligible is the default so a new language cannot be left behind (ISS-32)
export function advisoryEcosystemOf(filePath) {
  const prof = profileFor(filePath);
  if (!prof || prof.advisoryTier === false) return null;
  return prof.ecosystem ?? prof.id;
}

// cm:guard a marker counts only in COMMENT text. A file that quotes one in a regex or a string
//   literal is ordinary code, and testing raw source skipped this file and registry.mjs whole,
//   hiding every cm: annotation in both from every consumer (ISS-26). Do not name a marker
//   verbatim in a comment inside the first GENERATED_HEAD_LINES lines of any file: that comment
//   IS a header marker and the file skips itself.
// cm:guard the head SLICE is the whole of the window, and the window must never be bounded by a
//   comment's start line instead: a block carries one start line and text joined from all of them,
//   so bounding the start made a block opened on line 1 a header for its whole length and a marker
//   400 lines down skipped the file again — reachable by commenting out code that quotes a marker.
//   The golden cases are `late.ts` (a marker below the window) and `commented-out.ts` (a block
//   opened inside it); drop the slice and both fail.
// cm:why the marker is tested against the scanner's own joined text rather than a local re-join,
//   because a two-word marker legitimately spans two lines of one block header and `.*` never
//   crosses a newline — scan.mjs is the single authority on that normalisation
// cm:why the slice is scanned rather than the whole file: this rule exists for protobuf and bundler
//   output, and asking the question of the whole file cost 407 ms on a 3.89 MB generated file
//   where the slice costs 2 ms
export function isGenerated(src, prof) {
  const head = src.split('\n', GENERATED_HEAD_LINES).join('\n');
  const { comments } = scanComments(head, prof, { flushOpen: true });
  return comments.some((c) => c.text !== ''
    && GENERATED_MARKERS.some((re) => re.test(c.text)));
}
