// codemap/1 §6 — language profiles.
//
// docPolicy decides what happens to ORDINARY comments, and is the reason this framework can be
// dropped into ecosystems whose convention is the opposite of "few comments" (Go's godoc,
// Laravel's PHPStan docblocks) without being uninstalled on day one.
//
//   banned                -> a prose comment is CM001
//   allowed               -> prose comments are accepted; only cm: grammar is enforced
//   required-on-exported  -> a comment block directly above an exported declaration is exempt

import { scanComments } from './scan.mjs';
import { CM_IGNORE_RE } from './parse.mjs';

const COMMON_EXEMPT = [
  CM_IGNORE_RE,
  /^(Copyright|SPDX-License-Identifier)\b/i,
  /^@generated\b/,
];

const TS_EXEMPT = [
  /^@ts-(expect-error|ignore|nocheck|check)\b/,
  /^eslint-(disable|enable)/,
  /^biome-ignore\b/,
  /^i18n-allow\s*:/, // a consumer's own language gate requires this directive on non-English literals
  /^(prettier|dprint|deno-lint)-ignore\b/,
  /^(istanbul|c8|v8) ignore\b/,
  /^#(region|endregion)\b/,
  /^# sourceMappingURL=/,
  /^@__PURE__/,
  /^@(vite-ignore|jsx|jsxImportSource|vitest-environment|license|preserve)\b/,
  /^<reference\b/,
  /^@type\b/, // load-bearing under checkJs
];

const GO_EXEMPT = [
  /^go:[a-z]+/, // go:build, go:generate, go:embed
  /^\+build\b/,
  /^nolint\b/,
  /^lint:ignore\b/,
  /^export\s/, // cgo
  /^Deprecated:/,
];

const PHP_EXEMPT = [
  /^@(phpstan|psalm)-/,
  /^@(var|param|return|throws|deprecated|internal)\b/,
  /^phpcs:/,
  /^@codeCoverageIgnore/,
  /^@noinspection\b/,
  /^@SuppressWarnings\b/,
];

const PY_EXEMPT = [
  /^!/, // shebang
  /^-\*- coding/,
  /^coding[:=]/,
  /^type:\s/,
  /^noqa\b/,
  /^pragma:/,
  /^(pylint|mypy|ruff|pyright|isort|doctest):/,
  /^fmt:\s?(on|off)/,
  /^nosec\b/,
  /^black\b/,
];

const RUST_EXEMPT = [
  /^SAFETY:/, // clippy::undocumented_unsafe_blocks requires it
  /^rustfmt::skip/,
  /^clippy::/,
];

const SQL_EXEMPT = [
  /^>\s*statement-breakpoint/, // drizzle
  /^\+goose\b/,
  /^migrate:/,
];

const SH_EXEMPT = [/^!/, /^shellcheck\b/];

// cm:why Docker requires these three above everything else, so they cannot be moved below a header
//   comment and cannot be rewritten — the parser reads them, not a person
const DOCKER_EXEMPT = [/^syntax=/, /^escape=/, /^check=/];

/** How far into a file a generated-marker comment is still the file's own header. */
export const GENERATED_HEAD_LINES = 40;

/** A file whose head carries one of these is skipped entirely. */
export const GENERATED_MARKERS = [
  /Code generated .*DO NOT EDIT/,
  /@generated\b/,
  /AUTO[- ]GENERATED/i,
  /DO NOT EDIT THIS FILE/i,
  /_ide_helper/,
];

/**
 * strDelims  — quote characters, longest first (triple quotes before single).
 * multiline  — delimiters that legitimately span lines; every other one resets at EOL so a
 *              stray apostrophe in prose cannot desync the scanner for the rest of the file.
 */
const TS = {
  id: 'ts',
  // cm:why the RUNTIME, not the profile — §7.1 reads "different languages" as "cannot import each
  //   other", and an SFC imports .ts freely, so sfc inherits this and a literal they share is not a contract
  ecosystem: 'ts',
  lineLeaders: ['//'],
  docLineLeaders: [],
  blockOpens: [['/**', '*/'], ['/*', '*/']],
  docBlockOpens: ['/**'],
  strDelims: ['"', "'", '`'],
  multiline: ['`'],
  docPolicy: 'banned',
  // A /** */ block is documentation by form: the IDE surfaces it on hover, which is a consumer
  // with an immediate payoff (principle 1). Narration in a function body is the spam this exists
  // to kill, and that is always a line comment. So doc blocks are exempt and `//` prose is not —
  // simpler and more predictable than trying to decide which declarations deserve docs.
  docBlocksAllowed: true,
  // An ECMAScript directive prologue is the one construct the language itself requires ABOVE
  // everything else, so a header comment cannot get above it. Closed vocabulary (principle 3):
  // a general "string literal as a statement" rule would swallow a stray expression statement.
  prologue: /^\s*(['"])use (client|server|strict)\1\s*;?\s*$/,
  exempt: [...COMMON_EXEMPT, ...TS_EXEMPT],
};

const P = {
  ts: TS,
  // cm:why a template comments in HTML, not in TS's forms, and that is where a generator stamps a
  //   component's marker — without the form the marker is not comment text at all (ISS-28)
  // cm:guard exempt from prose BY FORM, never by a directive allowlist — a template has no per-site
  //   escape, so billing svelte-ignore would be a CM001 nobody can clear (ISS-28, rule in ISS-22)
  // cm:guard the spread comes FIRST — `id` after it, or TS's own id overwrites this profile's and
  //   every diagnostic, `cm ls` and `languages.sfc` silently address `ts` instead
  sfc: {
    ...TS,
    id: 'sfc',
    // cm:guard the region lives on the PROFILE, never on a `.vue` test in the printer — a new SFC extension must inherit it, and `//` in a
    //   template renders as visible text that cm verify accepts, so nothing downstream catches the paste (ISS-62, SPEC §6, remedy from ISS-28)
    leaderRegion: '<script>',
    // cm:why shares TS's ecosystem and is still out of CM301: no measurement has ever covered an SFC,
    //   and admitting one would warn in every consumer Vue repo as a side effect of a refactor (ISS-32)
    advisoryTier: false,
    blockOpens: [...TS.blockOpens, ['<!--', '-->']],
    proseExemptBlockOpens: ['<!--'],
  },
  go: {
    id: 'go',
    lineLeaders: ['//'],
    docLineLeaders: [],
    blockOpens: [['/*', '*/']],
    docBlockOpens: [],
    strDelims: ['"', '`'],
    multiline: ['`'],
    docPolicy: 'required-on-exported',
    // godoc requires a comment above the package clause and above every EXPORTED declaration —
    // and only those. An unexported func must not be exempt, or the policy exempts everything.
    // cm:guard `func\s*\(` is deliberately NOT a group opener here — that is a method receiver, and
    //   admitting it would exempt every unexported method too
    exportedDecl: /^(?:package\s+\w+|(?:type|const|var)\s*\(|(?:func|type|const|var)\s+(?:\(\s*\w+\s+\*?\w+\s*\)\s+)?[A-Z]\w*)/,
    // cm:why godoc renders a field's and a method's doc exactly as it renders a top-level one, so the
    //   position-only rule flagged 3036 blocks the ecosystem asks authors to write (ISS-10)
    exportedMember: /^[A-Z]\w*/,
    // cm:guard the member rule holds ONLY inside these — capitalisation alone would exempt narration above
    //   a same-package call like `DoThing()`, which is the in-body bucket the policy exists to catch
    memberBlock: /^(?:type\s+[A-Z]\w*\s*(?:=\s*)?(?:struct|interface)\b|type\s*\(|const\s*\(|var\s*\()/,
    exempt: [...COMMON_EXEMPT, ...GO_EXEMPT],
  },
  php: {
    id: 'php',
    lineLeaders: ['//', '#'],
    docLineLeaders: [],
    blockOpens: [['/**', '*/'], ['/*', '*/']],
    docBlockOpens: ['/**'],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    exempt: [...COMMON_EXEMPT, ...PHP_EXEMPT],
  },
  py: {
    id: 'py',
    lineLeaders: ['#'],
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"""', "'''", '"', "'"],
    multiline: ['"""', "'''"],
    docPolicy: 'allowed', // docstrings are strings, not comments — out of scope by construction
    exempt: [...COMMON_EXEMPT, ...PY_EXEMPT],
  },
  rust: {
    id: 'rust',
    lineLeaders: ['///', '//!', '//'],
    docLineLeaders: ['///', '//!'],
    blockOpens: [['/*', '*/']],
    docBlockOpens: [],
    strDelims: ['"'], // ' is a lifetime marker in Rust, never a string opener
    multiline: ['"'],
    docPolicy: 'allowed',
    exempt: [...COMMON_EXEMPT, ...RUST_EXEMPT],
  },
  sql: {
    id: 'sql',
    lineLeaders: ['--'],
    docLineLeaders: [],
    blockOpens: [['/*', '*/']],
    docBlockOpens: [],
    strDelims: ["'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false, // annotations still parsed, so sideeffect edges can sit next to a trigger
    // cm:why these four carry annotations without their prose being policed, and no CM301 measurement
    //   covers them; `enforce` is NOT the knob for it — that is prose grammar, overridable per repo
    advisoryTier: false,
    exempt: [...COMMON_EXEMPT, ...SQL_EXEMPT],
  },
  sh: {
    id: 'sh',
    lineLeaders: ['#'],
    // cm:edge contract -> cli/lib/scan.mjs — every `leaderAfter` in this file is read by beginsWord
    //   there and nowhere else, as a RegExp over the single character before the leader (ISS-61)
    // cm:why `${f#src/}` and `a#b` are one word, never a comment — shell ends a word at whitespace
    //   or a metacharacter, and reading the `#` as a leader masked the rest of the line (ISS-61)
    // cm:guard the backtick stays written \x60 — regex literals are not lexed here, so a LITERAL one
    //   opens a template string that swallows every annotation below it in this file (ISS-61)
    leaderAfter: /[\s;|&()<>\x60]/,
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false,
    // cm:why annotations are parsed here but prose is not policed, and no CM301 measurement
    //   covers this format — the same reason as sql's, stated where the flag is read
    advisoryTier: false,
    exempt: [...COMMON_EXEMPT, ...SH_EXEMPT],
  },
  yaml: {
    id: 'yaml',
    lineLeaders: ['#'],
    // cm:why a plain scalar ending in a word character swallows `#`, so `run#now` is one value; a
    //   QUOTED scalar or flow collection ends the token, and libyaml reads `key: "v"#c` as a comment
    // cm:guard this profile object also serves .toml, which narrows NOTHING — see the TOML entry in
    //   the extension map below before widening or reusing this (ISS-61)
    leaderAfter: /[\s"'\]},]/,
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false,
    // cm:why annotations are parsed here but prose is not policed, and no CM301 measurement
    //   covers this format — the same reason as sql's, stated where the flag is read
    advisoryTier: false,
    exempt: COMMON_EXEMPT,
  },
  docker: {
    // cm:why its own id rather than a reuse of yaml — it is the only profile whose exempt list carries
    //   Docker's parser directives, and `cm ls` prints the id, so reporting as yaml misnames it (ISS-25)
    id: 'docker',
    lineLeaders: ['#'],
    // cm:why `RUN echo a#b` carries no comment — Docker's own rule is stricter still, a comment being
    //   a whole line, so whitespace here is the safe half: a trailing `#` is still read as one (ISS-61)
    leaderAfter: /\s/,
    docLineLeaders: [],
    blockOpens: [],
    docBlockOpens: [],
    strDelims: ['"', "'"],
    multiline: [],
    docPolicy: 'allowed',
    enforce: false,
    // cm:why annotations are parsed here but prose is not policed, and no CM301 measurement
    //   covers this format — the same reason as sql's, stated where the flag is read
    advisoryTier: false,
    exempt: [...COMMON_EXEMPT, ...DOCKER_EXEMPT],
  },
};

// cm:why TOML reuses yaml's forms but must NOT reuse its leaderAfter — `port = 8080#c` is a comment
//   to TOML's own parser, and narrowing it would drop the annotation on that line (ISS-61)
// cm:edge lockstep -> cli/lib/scan.mjs — `leaderAfter` absent means "leader matches anywhere"; a
//   scanner that made the field mandatory would silently narrow TOML (ISS-61)
const TOML = { ...P.yaml, leaderAfter: undefined };

const BY_EXT = {
  ts: P.ts, tsx: P.ts, mts: P.ts, cts: P.ts,
  js: P.ts, jsx: P.ts, mjs: P.ts, cjs: P.ts,
  vue: P.sfc, svelte: P.sfc,
  go: P.go,
  php: P.php,
  py: P.py, pyi: P.py,
  rs: P.rust,
  sql: P.sql,
  sh: P.sh, bash: P.sh, zsh: P.sh,
  yaml: P.yaml, yml: P.yaml, toml: TOML,
};

const BY_BASENAME = {
  dockerfile: P.docker,
  containerfile: P.docker,
};

// cm:guard `<stem>.<variant>` takes an UNBOUNDED variant, so a stem here must be a word no
//   documentation or leftover file is named after — `.go` as a stem would swallow every Go file
const BASENAME_STEMS = Object.keys(BY_BASENAME);

// cm:why a documentation file is the one place a FALSE annotation outranks a missed one (§6): under a
//   `#` leader a fenced example `# cm:edge` becomes a real edge that fails a consumer's CI (ISS-25)
// cm:guard this deny-list is the only place to close that — `md` is in no profile, so it misses BY_EXT
//   and reaches the stem rules regardless, and no reordering of the lookup spares it (ISS-25)
// cm:guard every spelling of a format already here must be here too — `adoc` and `asciidoc` denied
//   while `asc` resolved is the same CM102 break wearing the third name for one format (ISS-25)
const DOC_EXT_DENY = new Set([
  'md', 'mdx', 'markdown', 'mkd', 'mdown', 'mdwn', 'mmd', 'mdtxt', 'markdn',
  'qmd', 'rmd', 'txt', 'text', 'rst', 'adoc', 'asciidoc', 'asc', 'textile', 'html', 'htm',
]);

// cm:why junk is what a conflicted merge or `patch` writes, holding the PRE-merge annotations, so a
//   variant whose last component is one is refused outright — `Dockerfile.orig` read as live (ISS-25)
// cm:guard only words meaning "not the real file" go here — `example`/`sample`/`dist` are committed on
//   purpose and must keep scanning; doc words are denied on ANY component, these only on the last
const JUNK_WORDS = new Set(['bak', 'orig', 'rej', 'save', 'swp', 'tmp', 'old']);

export const PROFILES = P;

// cm:guard split on the dot and judged per component, never on the trailing extension alone:
//   `Dockerfile.md.bak` is documentation whose doc word is not last, and a trailing-only test missed it
function variantWords(variant) {
  return variant.replace(/~+$/, '').split('.').filter(Boolean);
}

function docDenied(variant) {
  return variantWords(variant).some((w) => DOC_EXT_DENY.has(w));
}

/** A leftover an editor or a merge wrote — never the file the repository builds from. */
function isLeftover(variant) {
  if (/~$/.test(variant)) return true;
  const words = variantWords(variant);
  return words.length > 0 && JUNK_WORDS.has(words[words.length - 1]);
}

// cm:guard extension first, basename second — a hit in BY_EXT wins, or `x.yml` resolves by a stem
//   rule and every YAML file in the tree changes profile
// cm:guard this is the single authority on what is scannable; registry.mjs asks it rather than
//   restating it — a second SCAN_EXT list left Dockerfiles in `cm ls` and out of `cm verify` (ISS-25)
export function profileFor(filePath) {
  const base = String(filePath).split(/[\\/]/).pop() ?? '';
  const ext = /\.([a-z0-9]+)$/i.exec(base)?.[1]?.toLowerCase();
  if (ext && BY_EXT[ext]) return BY_EXT[ext];

  const lower = base.toLowerCase();
  if (BY_BASENAME[lower]) return BY_BASENAME[lower];

  for (const stem of BASENAME_STEMS) {
    let variant = null;
    if (lower.startsWith(`${stem}.`)) variant = lower.slice(stem.length + 1);
    else if (lower.endsWith(`.${stem}`)) variant = lower.slice(0, -(stem.length + 1));
    if (variant === null) continue;
    if (docDenied(variant) || isLeftover(variant)) return null;
    return BY_BASENAME[stem];
  }
  return null;
}

// cm:guard the SINGLE authority on which leader carries an annotation in a file — ask it, never write `//` into a suggestion; that was right
//   for ts by coincidence and a syntax error in every #-leader file, which is what cm propose printed (ISS-62)
// cm:guard skips a DOC leader by asking docLineLeaders, never by position — rust's lineLeaders[0] is `///`, and an annotation under it is
//   CM003 and dropped, so propose suggested a line verify then refused; a doc-only profile has no leader to offer and returns null (ISS-62)
// cm:edge contract -> cli/lib/scan.mjs — this trusts scanComments to stamp a docLineLeaders comment `kind: 'doc'`; a scanner that stopped
//   doing so would leave this skipping a leader that had become legal, which is stale rather than broken (ISS-62)
// cm:edge contract -> cli/lib/analyze.mjs — what makes a doc leader UNUSABLE is decided there, not in the scanner: any comment whose kind is
//   not 'line' carrying a cm: prefix becomes CM003 and is never parsed, so admitting one there is what would make this skip wrong (ISS-62)
// cm:why the profile is a parameter for its tests alone, as makeReserved's tags are: no profile in the tree has an empty lineLeaders, so no
//   assertion over the real ones reaches the null branch (ISS-62)
export function leaderFor(filePath, prof = profileFor(filePath)) {
  const docs = prof?.docLineLeaders ?? [];
  return (prof?.lineLeaders ?? []).find((l) => !docs.includes(l)) ?? null;
}

// cm:guard the leader for a template that belongs to NO file — `cm new` names a registry entry, so there is no host to ask, and
//   the answer is this tally and never a literal; a repo of `#` files got `//` from all three printers (ISS-63)
// cm:guard every leader here comes from leaderFor, so this holds no extension table of its own — a second one is the drift
//   ISS-32 measured at 5 lost extensions, and the caller must still SAY which leader it assumed (ISS-63)
// cm:why ties break on the leader string, not on iteration order, because the file list arrives from a directory walk whose
//   order is the filesystem's — an unstable tie would make the same repo print a different template run to run (ISS-63)
export function dominantLeader(files) {
  const tally = new Map();
  for (const rel of files) {
    const leader = leaderFor(rel);
    if (leader) tally.set(leader, (tally.get(leader) ?? 0) + 1);
  }
  const ranked = [...tally].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  const profiled = ranked.reduce((n, [, count]) => n + count, 0);
  if (!ranked.length) return { leader: null, files: 0, profiled: 0 };
  return { leader: ranked[0][0], files: ranked[0][1], profiled };
}

// cm:guard the SINGLE authority on "can these two files import each other" — ask it, never restate it
//   from a literal; a second extension-keyed table in graph.mjs silently lost 5 extensions (ISS-32)
export function ecosystemOf(filePath) {
  const prof = profileFor(filePath);
  return prof ? (prof.ecosystem ?? prof.id) : null;
}

// cm:guard a pair of files in different languages CANNOT reference each other — measured, that was 26 of
//   36 hits in one repo, so firing there is a bug in the check and not a threshold to tune (§7.1)
// cm:guard opt out on the PROFILE and never on the extension — a new BY_EXT entry must inherit its
//   profile's answer, and eligible is the default so a new language cannot be left behind (ISS-32)
export function advisoryEcosystemOf(filePath) {
  const prof = profileFor(filePath);
  if (!prof || prof.advisoryTier === false) return null;
  return prof.ecosystem ?? prof.id;
}

// cm:guard a marker counts only in COMMENT text — a file quoting one in a regex or a string literal is
//   ordinary code, and testing raw source skipped this file and registry.mjs whole (ISS-26)
// cm:guard never name a marker verbatim in a comment inside the first GENERATED_HEAD_LINES lines of any
//   file: that comment IS a header marker, and the file then skips itself (ISS-26)
// cm:guard the head SLICE is the whole of the window, never bounded by a comment's start line: a block
//   opened on line 1 would be a header for its whole length, skipping the file on a marker far below
// cm:edge lockstep -> tests/cases.mjs — `late.ts` and `commented-out.ts` pin that slice and both fail
//   if it goes, which is reachable by commenting out code that quotes a marker (ISS-26)
// cm:why the marker is tested against scan.mjs's own joined text, never a local re-join: a two-word
//   marker legitimately spans two lines of one block header and `.*` never crosses a newline
// cm:why the slice is scanned rather than the whole file: asking it of the whole file cost 407 ms on a
//   3.89 MB generated file where the slice costs 2 ms
export function isGenerated(src, prof) {
  const head = src.split('\n', GENERATED_HEAD_LINES).join('\n');
  const { comments } = scanComments(head, prof, { flushOpen: true });
  return comments.some((c) => GENERATED_MARKERS.some((re) => re.test(c.text)));
}
